export const Constants = {
    EMAIL_REQUIRED: 'Email Required',
    NAME_REQUIRED: 'Name Required',
    INVALID_EMAIL: 'Invalid Email Format',
    PASS_REQUIRED: 'Password Required',
    PASS_NOT_MATCH: 'Password Not Match',
    CHOOSE_STRONG_PASS: 'Choose Strong Password',
    MIN_LENGTH_PASS: 'Password must be at least 6 characters long',
    MIN_LENGTH_NAME: 'Name must be at least 3 characters long',
    SOMETHING_WENT_WRONG: 'Something Went Wrong',
    NETWORK_ERROR: 'Network Error, Please Check Your Connection',
    TOO_MANY_REQUEST: 'Too Many Requests. Please Slow Down',
    TOO_MANY_LOGIN_ATTEMPT: 'Too Many Login Attempts! Try After Some Time',
    TOO_MANY_SIGNUP_ATTEMPT: 'Too Many Signup Attempts! Try After Some Time',
    INVALID_EMAIL_PASSWORD: 'Invalid Email Or Password',
    EMAIL_SENT_SUCCESS: 'Email Sent Successfully',
    EMAIL_VERIFIED_SUCCESS: 'Email Verified Successfully',
    OTP_SENT_SUCCESS: 'OTP Sent Successfully',
    PASSWORD_RESET_SUCCESS: 'Password Reset Successfully',
    USER_NOT_FOUND: 'User Not Found',
    INVALID_LINK: 'Invalid Link',
    LINK_EXPIRED: 'Link Expired',
    INCORRECT_OTP: 'Incorrect OTP',
    OTP_EXPIRED: 'OTP has been expired',
    USER_ALREADY_EXISTS: 'User Already Exists',
    LOGGED_IN_SUCCESS: 'Logged In Successfully',
    SIGNUP_IN_SUCCESS: 'Signup In Successfully',
    LOGOUT_SUCCESS: 'Logged Out Successfully',
    SESSION_EXPIRED: 'Session expired. Please log in again',
    PLEASE_LOGIN_WITH_GOOGLE: 'This account is registered with Google. Please use sign in with Google',

}